/*
This code
1) Creates "Restaurant" record with id=1 in Industries,
2) Adds mock genres to Genres table
3) Matches yelpCategory to mock genre category
4) Pulls 20 restaurants using Yelp API and saves them into Establishments table

To run, uncomment code below and restart server. Once database is updated, comment out code

*/


var Yelp = require('yelp');
var db = require('../config/db');

var Industries = db.Industries;
var Genres = db.Genres;
var Establishments = db.Establishments;
var YelpCategories_Genres = db.YelpCategories_Genres;

// // Add Restaurant industry
// Industries.findOrCreate({where: {name: 'Restaurants'}})
//   .spread(function(industry, created) {
//     console.log(industry.get({
//       plain: true
//     }))
//     console.log(created)
//   });

// // Add "Genres" for restaurants
// var cuisingList = ['African','Asian','Mediterranean','Middle Eastern','Latin American','South American','Oceanian','North American','European'];
// cuisingList.sort();

// cuisingList.forEach(function(cuisine){
//   Genres.findOrCreate({where: {name: cuisine, industryId: 1}})
// })


// // Map yelpCategory to Genre for restaurants:
// var linkTable = [{yelpCategory: "afghani", genreId:6},
// {yelpCategory: "african", genreId:6},
// {yelpCategory: "senegalese", genreId:6},
// {yelpCategory: "southafrican", genreId:1},
// {yelpCategory: "newamerican", genreId:7},
// {yelpCategory: "tradamerican", genreId:7},
// {yelpCategory: "andalusian", genreId:5},
// {yelpCategory: "arabian", genreId:1},
// {yelpCategory: "arabpizza", genreId:1},
// {yelpCategory: "argentine", genreId:9},
// {yelpCategory: "armenian", genreId:4},
// {yelpCategory: "asianfusion", genreId:2},
// {yelpCategory: "asturian", genreId:4},
// {yelpCategory: "australian", genreId:8},
// {yelpCategory: "austrian", genreId:4},
// {yelpCategory: "baguettes", genreId:9},
// {yelpCategory: "bangladeshi", genreId:9},
// {yelpCategory: "bbq", genreId:7},
// {yelpCategory: "basque", genreId:7},
// {yelpCategory: "bavarian", genreId:4},
// {yelpCategory: "beergarden", genreId:4},
// {yelpCategory: "beerhall", genreId:4},
// {yelpCategory: "beisl", genreId:7},
// {yelpCategory: "belgian", genreId:7},
// {yelpCategory: "flemish", genreId:7},
// {yelpCategory: "bistros", genreId:7},
// {yelpCategory: "blacksea", genreId:7},
// {yelpCategory: "brasseries", genreId:7},
// {yelpCategory: "brazilian", genreId:7},
// {yelpCategory: "brazilianempanadas", genreId:7},
// {yelpCategory: "centralbrazilian", genreId:7},
// {yelpCategory: "northeasternbrazilian", genreId:7},
// {yelpCategory: "northernbrazilian", genreId:7},
// {yelpCategory: "rodizios", genreId:7},
// {yelpCategory: "breakfast_brunch", genreId:7},
// {yelpCategory: "british", genreId:7},
// {yelpCategory: "buffets", genreId:7},
// {yelpCategory: "bulgarian", genreId:7},
// {yelpCategory: "burgers", genreId:7},
// {yelpCategory: "burmese", genreId:7},
// {yelpCategory: "cafes", genreId:7},
// {yelpCategory: "cafeteria", genreId:7},
// {yelpCategory: "cajun", genreId:7},
// {yelpCategory: "cambodian", genreId:7},
// {yelpCategory: "newcanadian", genreId:7},
// {yelpCategory: "canteen", genreId:7},
// {yelpCategory: "caribbean", genreId:7},
// {yelpCategory: "dominican", genreId:7},
// {yelpCategory: "haitian", genreId:7},
// {yelpCategory: "puertorican", genreId:7},
// {yelpCategory: "trinidadian", genreId:7},
// {yelpCategory: "catalan", genreId:7},
// {yelpCategory: "cheesesteaks", genreId:7},
// {yelpCategory: "chickenshop", genreId:7},
// {yelpCategory: "chicken_wings", genreId:7},
// {yelpCategory: "chilean", genreId:7},
// {yelpCategory: "chinese", genreId:7},
// {yelpCategory: "cantonese", genreId:7},
// {yelpCategory: "congee", genreId:7},
// {yelpCategory: "dimsum", genreId:7},
// {yelpCategory: "fuzhou", genreId:7},
// {yelpCategory: "hakka", genreId:7},
// {yelpCategory: "henghwa", genreId:7},
// {yelpCategory: "hokkien", genreId:7},
// {yelpCategory: "hunan", genreId:7},
// {yelpCategory: "pekinese", genreId:7},
// {yelpCategory: "shanghainese", genreId:7},
// {yelpCategory: "szechuan", genreId:7},
// {yelpCategory: "teochew", genreId:7},
// {yelpCategory: "comfortfood", genreId:7},
// {yelpCategory: "corsican", genreId:7},
// {yelpCategory: "creperies", genreId:7},
// {yelpCategory: "cuban", genreId:7},
// {yelpCategory: "currysausage", genreId:7},
// {yelpCategory: "cypriot", genreId:7},
// {yelpCategory: "czech", genreId:7},
// {yelpCategory: "czechslovakian", genreId:7},
// {yelpCategory: "danish", genreId:7},
// {yelpCategory: "delis", genreId:7},
// {yelpCategory: "diners", genreId:7},
// {yelpCategory: "dumplings", genreId:7},
// {yelpCategory: "eastern_european", genreId:7},
// {yelpCategory: "ethiopian", genreId:7},
// {yelpCategory: "hotdogs", genreId:7},
// {yelpCategory: "filipino", genreId:7},
// {yelpCategory: "fischbroetchen", genreId:7},
// {yelpCategory: "fishnchips", genreId:7},
// {yelpCategory: "flatbread", genreId:7},
// {yelpCategory: "fondue", genreId:7},
// {yelpCategory: "food_court", genreId:7},
// {yelpCategory: "foodstands", genreId:7},
// {yelpCategory: "french", genreId:7},
// {yelpCategory: "alsatian", genreId:7},
// {yelpCategory: "auvergnat", genreId:7},
// {yelpCategory: "berrichon", genreId:7},
// {yelpCategory: "bourguignon", genreId:7},
// {yelpCategory: "nicois", genreId:7},
// {yelpCategory: "provencal", genreId:7},
// {yelpCategory: "sud_ouest", genreId:7},
// {yelpCategory: "galician", genreId:7},
// {yelpCategory: "gastropubs", genreId:7},
// {yelpCategory: "georgian", genreId:7},
// {yelpCategory: "german", genreId:7},
// {yelpCategory: "baden", genreId:7},
// {yelpCategory: "easterngerman", genreId:7},
// {yelpCategory: "hessian", genreId:7},
// {yelpCategory: "northerngerman", genreId:7},
// {yelpCategory: "palatine", genreId:7},
// {yelpCategory: "rhinelandian", genreId:7},
// {yelpCategory: "giblets", genreId:7},
// {yelpCategory: "gluten_free", genreId:7},
// {yelpCategory: "greek", genreId:7},
// {yelpCategory: "halal", genreId:7},
// {yelpCategory: "hawaiian", genreId:7},
// {yelpCategory: "heuriger", genreId:7},
// {yelpCategory: "himalayan", genreId:7},
// {yelpCategory: "hkcafe", genreId:7},
// {yelpCategory: "hotdog", genreId:7},
// {yelpCategory: "hotpot", genreId:7},
// {yelpCategory: "hungarian", genreId:7},
// {yelpCategory: "iberian", genreId:7},
// {yelpCategory: "indpak", genreId:7},
// {yelpCategory: "indonesian", genreId:7},
// {yelpCategory: "international", genreId:7},
// {yelpCategory: "irish", genreId:7},
// {yelpCategory: "island_pub", genreId:7},
// {yelpCategory: "israeli", genreId:7},
// {yelpCategory: "italian", genreId:7},
// {yelpCategory: "abruzzese", genreId:7},
// {yelpCategory: "altoatesine", genreId:7},
// {yelpCategory: "apulian", genreId:7},
// {yelpCategory: "calabrian", genreId:7},
// {yelpCategory: "cucinacampana", genreId:7},
// {yelpCategory: "emilian", genreId:7},
// {yelpCategory: "friulan", genreId:7},
// {yelpCategory: "ligurian", genreId:7},
// {yelpCategory: "lumbard", genreId:7},
// {yelpCategory: "napoletana", genreId:7},
// {yelpCategory: "piemonte", genreId:7},
// {yelpCategory: "roman", genreId:7},
// {yelpCategory: "sardinian", genreId:7},
// {yelpCategory: "sicilian", genreId:7},
// {yelpCategory: "tuscan", genreId:7},
// {yelpCategory: "venetian", genreId:7},
// {yelpCategory: "japanese", genreId:7},
// {yelpCategory: "blowfish", genreId:7},
// {yelpCategory: "conveyorsushi", genreId:7},
// {yelpCategory: "donburi", genreId:7},
// {yelpCategory: "gyudon", genreId:7},
// {yelpCategory: "oyakodon", genreId:7},
// {yelpCategory: "handrolls", genreId:7},
// {yelpCategory: "horumon", genreId:7},
// {yelpCategory: "izakaya", genreId:7},
// {yelpCategory: "japacurry", genreId:7},
// {yelpCategory: "kaiseki", genreId:7},
// {yelpCategory: "kushikatsu", genreId:7},
// {yelpCategory: "oden", genreId:7},
// {yelpCategory: "okinawan", genreId:7},
// {yelpCategory: "okonomiyaki", genreId:7},
// {yelpCategory: "onigiri", genreId:7},
// {yelpCategory: "ramen", genreId:7},
// {yelpCategory: "robatayaki", genreId:7},
// {yelpCategory: "soba", genreId:7},
// {yelpCategory: "sukiyaki", genreId:7},
// {yelpCategory: "takoyaki", genreId:7},
// {yelpCategory: "tempura", genreId:7},
// {yelpCategory: "teppanyaki", genreId:7},
// {yelpCategory: "tonkatsu", genreId:7},
// {yelpCategory: "udon", genreId:7},
// {yelpCategory: "unagi", genreId:7},
// {yelpCategory: "westernjapanese", genreId:7},
// {yelpCategory: "yakiniku", genreId:7},
// {yelpCategory: "yakitori", genreId:7},
// {yelpCategory: "jewish", genreId:7},
// {yelpCategory: "kebab", genreId:7},
// {yelpCategory: "kopitiam", genreId:7},
// {yelpCategory: "korean", genreId:7},
// {yelpCategory: "kosher", genreId:7},
// {yelpCategory: "kurdish", genreId:7},
// {yelpCategory: "laos", genreId:7},
// {yelpCategory: "laotian", genreId:7},
// {yelpCategory: "latin", genreId:7},
// {yelpCategory: "colombian", genreId:7},
// {yelpCategory: "salvadoran", genreId:7},
// {yelpCategory: "venezuelan", genreId:7},
// {yelpCategory: "raw_food", genreId:7},
// {yelpCategory: "lyonnais", genreId:7},
// {yelpCategory: "malaysian", genreId:7},
// {yelpCategory: "mamak", genreId:7},
// {yelpCategory: "nyonya", genreId:7},
// {yelpCategory: "meatballs", genreId:7},
// {yelpCategory: "mediterranean", genreId:7},
// {yelpCategory: "falafel", genreId:7},
// {yelpCategory: "mexican", genreId:7},
// {yelpCategory: "easternmexican", genreId:7},
// {yelpCategory: "jaliscan", genreId:7},
// {yelpCategory: "northernmexican", genreId:7},
// {yelpCategory: "oaxacan", genreId:7},
// {yelpCategory: "pueblan", genreId:7},
// {yelpCategory: "tacos", genreId:7},
// {yelpCategory: "tamales", genreId:7},
// {yelpCategory: "yucatan", genreId:7},
// {yelpCategory: "mideastern", genreId:7},
// {yelpCategory: "egyptian", genreId:7},
// {yelpCategory: "lebanese", genreId:7},
// {yelpCategory: "milkbars", genreId:7},
// {yelpCategory: "modern_australian", genreId:7},
// {yelpCategory: "modern_european", genreId:7},
// {yelpCategory: "mongolian", genreId:7},
// {yelpCategory: "moroccan", genreId:7},
// {yelpCategory: "newzealand", genreId:7},
// {yelpCategory: "nightfood", genreId:7},
// {yelpCategory: "norcinerie", genreId:7},
// {yelpCategory: "opensandwiches", genreId:7},
// {yelpCategory: "oriental", genreId:7},
// {yelpCategory: "pfcomercial", genreId:7},
// {yelpCategory: "pakistani", genreId:7},
// {yelpCategory: "eltern_cafes", genreId:7},
// {yelpCategory: "parma", genreId:7},
// {yelpCategory: "persian", genreId:7},
// {yelpCategory: "peruvian", genreId:7},
// {yelpCategory: "pita", genreId:7},
// {yelpCategory: "pizza", genreId:7},
// {yelpCategory: "polish", genreId:7},
// {yelpCategory: "pierogis", genreId:7},
// {yelpCategory: "portuguese", genreId:7},
// {yelpCategory: "alentejo", genreId:7},
// {yelpCategory: "algarve", genreId:7},
// {yelpCategory: "azores", genreId:7},
// {yelpCategory: "beira", genreId:7},
// {yelpCategory: "fado_houses", genreId:7},
// {yelpCategory: "madeira", genreId:7},
// {yelpCategory: "minho", genreId:7},
// {yelpCategory: "ribatejo", genreId:7},
// {yelpCategory: "tras_os_montes", genreId:7},
// {yelpCategory: "potatoes", genreId:7},
// {yelpCategory: "poutineries", genreId:7},
// {yelpCategory: "pubfood", genreId:7},
// {yelpCategory: "riceshop", genreId:7},
// {yelpCategory: "romanian", genreId:7},
// {yelpCategory: "rotisserie_chicken", genreId:7},
// {yelpCategory: "rumanian", genreId:7},
// {yelpCategory: "russian", genreId:7},
// {yelpCategory: "salad", genreId:7},
// {yelpCategory: "sandwiches", genreId:7},
// {yelpCategory: "scandinavian", genreId:7},
// {yelpCategory: "scottish", genreId:7},
// {yelpCategory: "seafood", genreId:7},
// {yelpCategory: "serbocroatian", genreId:7},
// {yelpCategory: "signature_cuisine", genreId:7},
// {yelpCategory: "singaporean", genreId:7},
// {yelpCategory: "slovakian", genreId:7},
// {yelpCategory: "soulfood", genreId:7},
// {yelpCategory: "soup", genreId:7},
// {yelpCategory: "southern", genreId:7},
// {yelpCategory: "spanish", genreId:7},
// {yelpCategory: "arroceria_paella", genreId:7},
// {yelpCategory: "srilankan", genreId:7},
// {yelpCategory: "steak", genreId:7},
// {yelpCategory: "supperclubs", genreId:7},
// {yelpCategory: "sushi", genreId:7},
// {yelpCategory: "swabian", genreId:7},
// {yelpCategory: "swedish", genreId:7},
// {yelpCategory: "swissfood", genreId:7},
// {yelpCategory: "syrian", genreId:7},
// {yelpCategory: "tabernas", genreId:7},
// {yelpCategory: "taiwanese", genreId:7},
// {yelpCategory: "tapas", genreId:7},
// {yelpCategory: "tapasmallplates", genreId:7},
// {yelpCategory: "tex-mex", genreId:7},
// {yelpCategory: "thai", genreId:7},
// {yelpCategory: "norwegian", genreId:7},
// {yelpCategory: "traditional_swedish", genreId:7},
// {yelpCategory: "trattorie", genreId:7},
// {yelpCategory: "turkish", genreId:7},
// {yelpCategory: "cheekufta", genreId:7},
// {yelpCategory: "gozleme", genreId:7},
// {yelpCategory: "homemadefood", genreId:7},
// {yelpCategory: "lahmacun", genreId:7},
// {yelpCategory: "turkishravioli", genreId:7},
// {yelpCategory: "ukrainian", genreId:7},
// {yelpCategory: "uzbek", genreId:7},
// {yelpCategory: "vegan", genreId:7},
// {yelpCategory: "vegetarian", genreId:7},
// {yelpCategory: "venison", genreId:7},
// {yelpCategory: "vietnamese", genreId:7},
// {yelpCategory: "wok", genreId:7},
// {yelpCategory: "wraps", genreId:7},
// {yelpCategory: "yugoslav", genreId:7}];


// linkTable.forEach(function(link){
//   YelpCategories_Genres.findOrCreate({where: {yelpCategory: link.yelpCategory, genreId: link.genreId}})
// })


// var yelp = new Yelp({
//   consumer_key: 'FW8Mc7pREwM4wb6tDXCqQQ',
//   consumer_secret: 'NWuduUH_hygivccfEywP51nEzA0',
//   token: 'SEDzj2ONG-liWR0U-0MfmWlYXl2NM-tP',
//   token_secret: 'YcJRVQiAt4m9unwCH_VK1JhLAjo',
// });

// yelp.search({ term: '', location: 'San Francisco', limit: 20})
//   .then(function (dataset) {
//     dataset.businesses.forEach(function(item){
//       var addEstablishment = function(genreId){
//         Establishments.findOrCreate({where: {
//                             name: item.name,
//                             imageUrl: item.image_url,
//                             yelpUrl: item.url,
//                             yelpId: item.id,
//                             yelpRating: item.rating,
//                             yelpReviewCount: item.review_count,
//                             genreId: genreId,
//                             zoneLat: 0,
//                             zoneLon: 0,
//                             latitude: item.location.coordinate.latitude,
//                             longitude: item.location.coordinate.longitude,
//                             address: item.location.address[0] + ', ' + item.location.city + ', ' + item.location.state_code + ' ' + item.location.postal_code,
//                             phoneNumber: item.display_phone,
//                             industryId: 1
//                           }})
//       };
//       YelpCategories_Genres.findOne({where: {yelpCategory: item.categories[0][1]}})
//                       .then(function(row){
//                         var genreId = !!row ? row.dataValues.genreId : 7;
//                         addEstablishment(genreId);
//                       });
//     })
//   })
//   .catch(function (err) {
//     console.error(err);
//   });

